//
//  APKDVRTaskId.h
//  AITBrain
//
//  Created by Mac on 17/3/20.
//  Copyright © 2017年 APK. All rights reserved.
//

#ifndef APKDVRTaskId_h
#define APKDVRTaskId_h

#define TAKE_PHOTO_ID 1
#define RECORD_EVENT_ID 2
#define GET_PHOTO_LIST_ID 3
#define GET_VIDEO_LIST_ID 4
#define GET_EVENT_LIST_ID 5
#define GET_LIVE_INFO_ID 6
#define DELETE_FILE_ID 7
#define GET_WIFI_INFO_ID 8
#define MODIFY_WIFI_ID 9
#define UPDATE_WIFI_ID 10
#define FIND_ME_ID 11
#define GET_RECORD_STATE_ID 12
#define GET_SETTING_INFO_ID 13
#define SET_DVR_ID 14
#define GET_DVR_ID 15
#define CHECK_REAR_CAMERA_ID 16
#define SET_REAR_CAMERA_ID 17
#define SET_FONT_CAMERA_ID 18
#define TOGGLE_RECORED_STATE_ID 19


#define GET_PARK_TIME_LIST 20//新增
#define GET_PARK_EVENT_LIST 21

#define GET_LOGIN_TOKEN 22

#define GET_CAMERA_INFO 23


////REC
//#define SET_VIDEO_RESOLUTION_ID 14
//#define SET_VIDEO_CLIP_DURATION_ID 15
//#define SET_SCREEN_ID 16
//#define SET_RECORD_SOUND_ID 17
//#define SET_COLLISION_DETECTION_ID 18
//#define SET_TIME_MARK_ID 19
//#define SET_PARKING_MODE_ID 20
//#define SET_POWER_FREQUENCY_ID 21
//#define SET_EXPOSURE_VALUE_ID 22
////FILE
//#define SET_FORMAT_ID 23
//#define SET_SDCARD_INFO_ID 24
////SET
//#define SET_TIME_ID 25
//#define SET_TIME_ZONE_ID 26
//#define SET_SATELLITE_TIME_SYNC_ID 27
//#define SET_SOUND_EFFECT_ID 28
//#define SET_VOLUME_ID 29
//#define SET_LANGUAGE_ID 30
////ADV
//#define SET_VELOCITY_UNIT_ID 31
//#define SET_CUSTOM_SPEED_LIMIT_TIPS_ID 32
//#define SET_SPEED_CAMERA_TIPS_ID 33
//#define SET_CUSTOM_SPEED_POINT_MANAGEMENT_ID 34
//#define SET_FACTORYRESET_ID 35

//#define FORMAT_SDCARD_ID 9
//#define UPDATE_DVR_CLOCK_ID 12
//#define FACTORYRESET_ID 13
//#define SET_MIC_ID 16
//#define SET_CLIP_DURATION_ID 17
//#define SET_G_SENSOR_ID 18

#endif /* APKDVRTaskId_h */
